"""
Régénère YOLO Smart Traffic Benchmark.ipynb pour Google Colab Pro
- Garde la même structure que l'original
- Ajoute : Drive, Kaggle API, Keep-alive, sauvegarde Drive
"""
import json
from pathlib import Path

def md(source):
    return {"cell_type":"markdown","metadata":{},"source":[source]}

def code(lines):
    if isinstance(lines, str):
        lines = [lines]
    return {"cell_type":"code","execution_count":None,"metadata":{},"outputs":[],"source":lines}

# ─────────────────────────────────────────────────────────────────
CELL_TITLE = md(
    "# 🚦 YOLO Smart Traffic Agadir — Benchmark Complet (Dataset V2)\n"
    "**Modèles** : YOLOv8n · YOLOv11n · YOLO26n — **150 epochs**  \n"
    "**Plateforme** : Google Colab Pro (A100 recommandé)  \n"
    "✅ Sauvegarde Drive après chaque modèle  \n"
    "✅ Reprise automatique si session coupée  \n"
    "✅ Keep-alive anti-déconnexion  \n"
    "✅ Export ONNX + tableau comparatif final"
)

CELL_SETUP = code([
    "# ═══ SETUP ═══════════════════════════════════════════════════\n",
    "import subprocess, sys, os, time, shutil, json, glob, yaml, threading\n",
    "from pathlib import Path\n",
    "\n",
    "subprocess.run([sys.executable,'-m','pip','install','ultralytics','kaggle','-q'],\n",
    "               capture_output=True)\n",
    "\n",
    "from ultralytics import YOLO, settings\n",
    "settings.update({'mlflow': False})\n",
    "import torch\n",
    "\n",
    "print(f'GPU  : {torch.cuda.get_device_name(0)}')\n",
    "print(f'VRAM : {torch.cuda.get_device_properties(0).total_memory/1e9:.1f} GB')\n",
    "print(f'CUDA : {torch.version.cuda}')\n",
])

CELL_DRIVE = code([
    "# ═══ GOOGLE DRIVE ════════════════════════════════════════════\n",
    "from google.colab import drive\n",
    "drive.mount('/content/drive')\n",
    "\n",
    "# ── Chemins ───────────────────────────────────────────────────\n",
    "DRIVE_BASE    = '/content/drive/MyDrive/SmartTraffic'\n",
    "DRIVE_CKPT    = f'{DRIVE_BASE}/checkpoints'\n",
    "DRIVE_RESULTS = f'{DRIVE_BASE}/benchmark_results'\n",
    "WORKING       = '/content/smart_traffic'\n",
    "RUNS          = f'{WORKING}/runs'\n",
    "DATA_DIR      = f'{WORKING}/dataset_v2'\n",
    "DATA_YAML     = f'{WORKING}/data.yaml'\n",
    "RESULTS_FILE  = f'{DRIVE_RESULTS}/benchmark_results_v2.json'\n",
    "\n",
    "for d in [WORKING, RUNS, DRIVE_CKPT, DRIVE_RESULTS]:\n",
    "    os.makedirs(d, exist_ok=True)\n",
    "\n",
    "print('✅ Drive monté')\n",
    "print(f'   Résultats → {DRIVE_RESULTS}')\n",
    "print(f'   Checkpoints → {DRIVE_CKPT}')\n",
])

CELL_DATASET = code([
    "# ═══ DATASET (Kaggle API) ════════════════════════════════════\n",
    "import zipfile\n",
    "\n",
    "KAGGLE_USERNAME = 'mouadassargual'\n",
    "KAGGLE_KEY      = 'COLLE_TA_CLÉ_ICI'   # kaggle.com/settings → API → Create Token\n",
    "\n",
    "os.makedirs('/root/.config/kaggle', exist_ok=True)\n",
    "with open('/root/.config/kaggle/kaggle.json','w') as f:\n",
    "    json.dump({'username': KAGGLE_USERNAME, 'key': KAGGLE_KEY}, f)\n",
    "os.chmod('/root/.config/kaggle/kaggle.json', 0o600)\n",
    "\n",
    "if not os.path.isdir(f'{DATA_DIR}/images/val'):\n",
    "    print('📥 Téléchargement dataset depuis Kaggle...')\n",
    "    ret = os.system(f'kaggle datasets download {KAGGLE_USERNAME}/smart-traffic-v2 -p {WORKING}')\n",
    "    if ret != 0:\n",
    "        raise RuntimeError('❌ Erreur — vérifie ta clé API Kaggle')\n",
    "    zip_p = f'{WORKING}/smart-traffic-v2.zip'\n",
    "    print('📦 Extraction...')\n",
    "    with zipfile.ZipFile(zip_p,'r') as z:\n",
    "        z.extractall(WORKING)\n",
    "    os.remove(zip_p)\n",
    "    print('✅ Dataset extrait')\n",
    "else:\n",
    "    print('✅ Dataset déjà présent — skip')\n",
    "\n",
    "# Auto-détecter data.yaml\n",
    "res = subprocess.run(['find', WORKING, '-name','data.yaml'], capture_output=True, text=True)\n",
    "yaml_files = [f for f in res.stdout.strip().split('\\n') if f]\n",
    "if not yaml_files:\n",
    "    raise FileNotFoundError('data.yaml introuvable')\n",
    "\n",
    "DATA_YAML_SRC = yaml_files[0]\n",
    "DATA_DIR      = str(Path(DATA_YAML_SRC).parent)\n",
    "print(f'data.yaml → {DATA_YAML_SRC}')\n",
    "\n",
    "with open(DATA_YAML_SRC) as f:\n",
    "    data = yaml.safe_load(f)\n",
    "\n",
    "# Trouver les vrais chemins images\n",
    "def find_split(name):\n",
    "    r = subprocess.run(['find', WORKING, '-type','d','-name', name],\n",
    "                       capture_output=True, text=True)\n",
    "    paths = [p for p in r.stdout.strip().split('\\n') if p and 'images' in p]\n",
    "    return paths[0] if paths else f'{DATA_DIR}/images/{name}'\n",
    "\n",
    "data['train'] = find_split('train')\n",
    "data['val']   = find_split('val')\n",
    "data['test']  = find_split('test')\n",
    "data.pop('path', None)\n",
    "\n",
    "DATA_YAML = f'{DATA_DIR}/data.yaml'\n",
    "with open(DATA_YAML,'w') as f:\n",
    "    yaml.dump(data, f, default_flow_style=False, allow_unicode=True)\n",
    "\n",
    "print(f'Classes ({data[\"nc\"]}) : {data[\"names\"]}')\n",
    "total = 0\n",
    "for split in ['train','val','test']:\n",
    "    p = Path(data[split])\n",
    "    n = len(list(p.glob('*.[jp][pn]g'))) if p.exists() else 0\n",
    "    icon = '✅' if n > 0 else '❌'\n",
    "    print(f'  {icon} {split:5s}: {n:,} images')\n",
    "    total += n\n",
    "print(f'  TOTAL: {total:,} images')\n",
])

CELL_KEEPALIVE = code([
    "# ═══ KEEP-ALIVE (anti-déconnexion Colab) ════════════════════\n",
    "_ka_stop = threading.Event()\n",
    "\n",
    "def _keepalive():\n",
    "    i = 0\n",
    "    while not _ka_stop.is_set():\n",
    "        print(f'💓 alive {i} — {time.strftime(\"%H:%M:%S\")}', flush=True)\n",
    "        i += 1\n",
    "        time.sleep(60)\n",
    "\n",
    "_t = threading.Thread(target=_keepalive, daemon=True)\n",
    "_t.start()\n",
    "print('✅ Keep-alive démarré')\n",
])

CELL_EXISTING = code([
    "# ═══ RÉSULTATS EXISTANTS (chargés depuis Drive) ══════════════\n",
    "if os.path.exists(RESULTS_FILE):\n",
    "    with open(RESULTS_FILE) as f:\n",
    "        RESULTS = json.load(f)\n",
    "    print(f'Résultats chargés depuis Drive : {list(RESULTS.keys())}')\n",
    "    for name, r in RESULTS.items():\n",
    "        print(f'  {name:<17} mAP50={r[\"mAP50\"]}%  ({r[\"duration\"]})')\n",
    "else:\n",
    "    RESULTS = {}\n",
    "    print('Nouveau benchmark — aucun résultat existant')\n",
])

CELL_TRAIN = code([
    "# ═══ TRAINING (3 MODÈLES + SAUVEGARDE DRIVE) ════════════════\n",
    "\n",
    "def save_to_drive(run_name, run_dir):\n",
    "    \"\"\"Sauvegarde checkpoint + figures sur Drive\"\"\"\n",
    "    dst_c = f'{DRIVE_CKPT}/{run_name}'\n",
    "    dst_f = f'{DRIVE_RESULTS}/figures/{run_name}'\n",
    "    os.makedirs(dst_c, exist_ok=True)\n",
    "    os.makedirs(dst_f, exist_ok=True)\n",
    "    saved = 0\n",
    "    for fname in ['last.pt','best.pt']:\n",
    "        src = f'{run_dir}/weights/{fname}'\n",
    "        if os.path.exists(src):\n",
    "            shutil.copy2(src, f'{dst_c}/{fname}')\n",
    "            saved += 1\n",
    "    for pat in ['*.png','*.jpg','*.csv']:\n",
    "        for f in glob.glob(f'{run_dir}/{pat}'):\n",
    "            shutil.copy2(f, dst_f)\n",
    "            saved += 1\n",
    "    print(f'   💾 Drive: {saved} fichiers ({run_name})')\n",
    "\n",
    "def restore_from_drive(run_name):\n",
    "    \"\"\"Restaure last.pt depuis Drive si pas en local\"\"\"\n",
    "    local = f'{RUNS}/{run_name}/weights/last.pt'\n",
    "    src   = f'{DRIVE_CKPT}/{run_name}/last.pt'\n",
    "    if not os.path.exists(local) and os.path.exists(src):\n",
    "        os.makedirs(f'{RUNS}/{run_name}/weights', exist_ok=True)\n",
    "        shutil.copy2(src, local)\n",
    "        best_src = f'{DRIVE_CKPT}/{run_name}/best.pt'\n",
    "        if os.path.exists(best_src):\n",
    "            shutil.copy2(best_src, f'{RUNS}/{run_name}/weights/best.pt')\n",
    "        print(f'   🔄 Checkpoint restauré depuis Drive')\n",
    "    return os.path.exists(local)\n",
    "\n",
    "MODELS = {\n",
    "    'yolov8n_v2' : 'yolov8n.pt',\n",
    "    'yolov11n_v2': 'yolo11n.pt',\n",
    "    'yolo26n_v2' : 'yolo26n.pt',\n",
    "}\n",
    "\n",
    "for name, weights in MODELS.items():\n",
    "\n",
    "    if name in RESULTS:\n",
    "        print(f'\\n⏭️  {name} déjà terminé (mAP50={RESULTS[name][\"mAP50\"]}%) — skip')\n",
    "        continue\n",
    "\n",
    "    print(f'\\n{\"=\"*58}')\n",
    "    print(f'  🚀 Training : {name}')\n",
    "    print(f'{\"=\"*58}')\n",
    "\n",
    "    has_ckpt = restore_from_drive(name)\n",
    "    src_w    = f'{RUNS}/{name}/weights/last.pt' if has_ckpt else weights\n",
    "    resume   = has_ckpt\n",
    "    print(f'  Resume={resume} | weights={src_w}')\n",
    "\n",
    "    model = YOLO(src_w)\n",
    "    t0    = time.time()\n",
    "\n",
    "    res = model.train(\n",
    "        data=DATA_YAML, epochs=150, batch=32, imgsz=640,\n",
    "        patience=25, optimizer='AdamW', lr0=0.001, lrf=0.01,\n",
    "        warmup_epochs=5, amp=True, cache='ram',\n",
    "        device=0, project=RUNS, name=name,\n",
    "        save_period=5, exist_ok=True, resume=resume,\n",
    "        plots=True, verbose=True,\n",
    "        mosaic=1.0, mixup=0.1, copy_paste=0.1,\n",
    "        hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, fliplr=0.5,\n",
    "    )\n",
    "\n",
    "    dur = time.time() - t0\n",
    "    h, m = int(dur//3600), int((dur%3600)//60)\n",
    "\n",
    "    try:\n",
    "        rd      = res.results_dict\n",
    "        map50   = round(rd.get('metrics/mAP50(B)',    0)*100, 2)\n",
    "        map5095 = round(rd.get('metrics/mAP50-95(B)',0)*100, 2)\n",
    "        prec    = round(rd.get('metrics/precision(B)',0)*100, 2)\n",
    "        recall  = round(rd.get('metrics/recall(B)',   0)*100, 2)\n",
    "    except:\n",
    "        map50 = map5095 = prec = recall = 0\n",
    "\n",
    "    class_metrics = {}\n",
    "    try:\n",
    "        val_r = model.val(data=DATA_YAML, verbose=False)\n",
    "        for i, cls in enumerate(data['names']):\n",
    "            class_metrics[cls] = round(float(val_r.box.ap50[i])*100, 2)\n",
    "    except Exception as e:\n",
    "        print(f'  ⚠️ métriques par classe: {e}')\n",
    "\n",
    "    RESULTS[name] = {\n",
    "        'mAP50'  : map50,\n",
    "        'mAP5095': map5095,\n",
    "        'prec'   : prec,\n",
    "        'recall' : recall,\n",
    "        'duration': f'{h}h {m}m',\n",
    "        'dataset_version': 'v2',\n",
    "        'classes': class_metrics,\n",
    "    }\n",
    "\n",
    "    # ✅ Sauvegarde immédiate sur Drive\n",
    "    with open(RESULTS_FILE,'w') as f:\n",
    "        json.dump(RESULTS, f, indent=2, ensure_ascii=False)\n",
    "    save_to_drive(name, f'{RUNS}/{name}')\n",
    "\n",
    "    print(f'\\n✅ {name} terminé ({h}h {m}m)')\n",
    "    print(f'   mAP@50    : {map50}%')\n",
    "    print(f'   mAP@50-95 : {map5095}%')\n",
    "    for cls, v in class_metrics.items():\n",
    "        icon = '✅' if v>=90 else ('⚠️' if v>=70 else '❌')\n",
    "        bar  = '█' * int(v/5)\n",
    "        print(f'   {icon} {cls:<22}: {v:.1f}%  {bar}')\n",
    "\n",
    "_ka_stop.set()\n",
    "print('\\n🏁 Training complet !')\n",
])

CELL_EXPORT = code([
    "# ═══ EXPORT ONNX (meilleur modèle → Drive) ══════════════════\n",
    "if RESULTS:\n",
    "    best_name = max(RESULTS, key=lambda x: RESULTS[x]['mAP50'])\n",
    "    best_pt   = f'{RUNS}/{best_name}/weights/best.pt'\n",
    "    print(f'🏆 Meilleur : {best_name}  mAP50={RESULTS[best_name][\"mAP50\"]}%')\n",
    "    if os.path.exists(best_pt):\n",
    "        m    = YOLO(best_pt)\n",
    "        onnx = m.export(format='onnx', imgsz=640, simplify=True, opset=12)\n",
    "        dst_onnx = f'{DRIVE_RESULTS}/best_{best_name}.onnx'\n",
    "        dst_pt   = f'{DRIVE_RESULTS}/best_{best_name}.pt'\n",
    "        shutil.copy2(str(onnx), dst_onnx)\n",
    "        shutil.copy2(best_pt, dst_pt)\n",
    "        print(f'✅ ONNX : {os.path.getsize(dst_onnx)/1e6:.1f} MB → Drive')\n",
    "        print(f'✅ PT   → Drive')\n",
    "    else:\n",
    "        print(f'⚠️  best.pt introuvable : {best_pt}')\n",
])

CELL_TABLE = code([
    "# ═══ TABLEAU FINAL DES 3 MODÈLES ════════════════════════════\n",
    "if os.path.exists(RESULTS_FILE):\n",
    "    with open(RESULTS_FILE) as f:\n",
    "        RESULTS = json.load(f)\n",
    "\n",
    "print('='*65)\n",
    "print('  📊 BENCHMARK — Smart Traffic Agadir (Dataset V2)')\n",
    "print('='*65)\n",
    "print(f'{\"Modèle\":<17} {\"mAP@50\":>8} {\"mAP50-95\":>9} {\"Prec\":>7} {\"Recall\":>7} {\"Durée\":>8}')\n",
    "print('-'*65)\n",
    "for name, r in RESULTS.items():\n",
    "    star = ' ← BEST' if name == max(RESULTS, key=lambda x: RESULTS[x]['mAP50']) else ''\n",
    "    print(f'{name:<17} {r[\"mAP50\"]:>7.2f}% {r[\"mAP5095\"]:>8.2f}%'\n",
    "          f' {r[\"prec\"]:>6.2f}% {r[\"recall\"]:>6.2f}% {r[\"duration\"]:>8}{star}')\n",
    "print('='*65)\n",
    "\n",
    "best = max(RESULTS, key=lambda x: RESULTS[x]['mAP50'])\n",
    "print(f'\\n🏆 Meilleur modèle : {best}  ({RESULTS[best][\"mAP50\"]}%)')\n",
    "print('\\nDétail par classe :')\n",
    "classes = ['car','bus','truck','motorcycle','person','emergency_vehicle']\n",
    "for cls in classes:\n",
    "    row = f'  {cls:<22}'\n",
    "    for name in RESULTS:\n",
    "        v = RESULTS[name].get('classes',{}).get(cls, 0)\n",
    "        row += f'  {name[-4:]}={v:.1f}%'\n",
    "    print(row)\n",
    "\n",
    "print(f'\\n📁 Fichiers sauvegardés dans Drive :')\n",
    "print(f'   {DRIVE_RESULTS}/')\n",
    "print(f'   ├── benchmark_results_v2.json')\n",
    "print(f'   ├── best_*.pt / best_*.onnx')\n",
    "print(f'   └── figures/(yolov8n_v2|yolov11n_v2|yolo26n_v2)/')\n",
])

# ── Build notebook ────────────────────────────────────────────
nb = {
    "nbformat": 4,
    "nbformat_minor": 4,
    "metadata": {
        "kernelspec": {"display_name":"Python 3","language":"python","name":"python3"},
        "language_info": {"name":"python","version":"3.10.0"},
        "accelerator": "GPU",
        "colab": {"provenance": [], "gpuType": "A100"}
    },
    "cells": [
        CELL_TITLE,
        md("## ⚙️ Setup"),
        CELL_SETUP,
        md("## 📁 Google Drive\n> Tout sera sauvegardé dans `MyDrive/SmartTraffic/benchmark_results/`"),
        CELL_DRIVE,
        md("## 📦 Dataset (Kaggle API)\n> **Avant de lancer** : remplace `COLLE_TA_CLÉ_ICI` par ta clé API Kaggle  \n> → [kaggle.com/settings](https://www.kaggle.com/settings) → API → **Create New Token**"),
        CELL_DATASET,
        md("## 💓 Keep-Alive (anti-déconnexion)"),
        CELL_KEEPALIVE,
        md("## 📊 Résultats existants (chargés depuis Drive)"),
        CELL_EXISTING,
        md("## 🚀 Training — 3 modèles × 150 epochs\n> ⏱️ Estimé : **~15h T4** | **~8h V100** | **~6h A100**  \n> ✅ Sauvegarde automatique sur Drive après chaque modèle  \n> ✅ Reprise depuis Drive si session coupée"),
        CELL_TRAIN,
        md("## 📤 Export ONNX"),
        CELL_EXPORT,
        md("## 🏆 Tableau comparatif final"),
        CELL_TABLE,
    ]
}

out = Path('/Users/mouadassargual/Desktop/smart-traffic-agadir/YOLO Smart Traffic Benchmark.ipynb')
with open(out,'w',encoding='utf-8') as f:
    json.dump(nb, f, indent=1, ensure_ascii=False)

sz = out.stat().st_size / 1024
print(f"Notebook mis à jour : {out}")
print(f"Taille  : {sz:.1f} KB")
print(f"Cellules: {len(nb['cells'])}")
